# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timetable.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(580, 280)
        widget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        widget.setWindowOpacity(0.9)
        self.box_edit = QtWidgets.QFrame(widget)
        self.box_edit.setGeometry(QtCore.QRect(0, 0, 580, 280))
        self.box_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_edit.setObjectName("box_edit")
        self.box_select = QtWidgets.QFrame(self.box_edit)
        self.box_select.setEnabled(False)
        self.box_select.setGeometry(QtCore.QRect(140, 10, 431, 151))
        self.box_select.setStyleSheet("QFrame {\n"
"    background-color: white\n"
"}\n"
"QFrame QPushButton {\n"
"    background-color: #eee;\n"
"    border: none;\n"
"}\n"
"QFrame QPushButton::checked {\n"
"    background-color:rgb(160, 200, 160);\n"
"    border: 2px solid #08F;\n"
"    image: url(:/checked.png);\n"
"}\n"
"QFrame QPushButton::hover {\n"
"    border: 2px solid #0AF;\n"
"}")
        self.box_select.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.box_select.setFrameShadow(QtWidgets.QFrame.Raised)
        self.box_select.setObjectName("box_select")
        self.label_6 = QtWidgets.QLabel(self.box_select)
        self.label_6.setGeometry(QtCore.QRect(220, 10, 62, 31))
        self.label_6.setStyleSheet("border: 1px solid #bbb;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.box_select)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 62, 31))
        self.label_2.setStyleSheet("border: 1px solid #bbb;")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.box_select)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 62, 40))
        self.label_3.setStyleSheet("border: 1px solid #bbb;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.box_select)
        self.label_5.setGeometry(QtCore.QRect(150, 10, 62, 31))
        self.label_5.setStyleSheet("border: 1px solid #bbb;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.box_select)
        self.label.setGeometry(QtCore.QRect(80, 10, 62, 31))
        self.label.setStyleSheet("border: 1px solid #bbb;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.box_select)
        self.label_8.setGeometry(QtCore.QRect(360, 10, 62, 31))
        self.label_8.setStyleSheet("border: 1px solid #bbb;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.box_select)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 62, 40))
        self.label_4.setStyleSheet("border: 1px solid #bbb;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.box_select)
        self.label_7.setGeometry(QtCore.QRect(290, 10, 62, 31))
        self.label_7.setStyleSheet("border: 1px solid #bbb;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.btn_a1 = QtWidgets.QPushButton(self.box_select)
        self.btn_a1.setGeometry(QtCore.QRect(80, 50, 62, 40))
        self.btn_a1.setText("")
        self.btn_a1.setCheckable(True)
        self.btn_a1.setChecked(False)
        self.btn_a1.setObjectName("btn_a1")
        self.btn_a2 = QtWidgets.QPushButton(self.box_select)
        self.btn_a2.setGeometry(QtCore.QRect(150, 50, 62, 40))
        self.btn_a2.setText("")
        self.btn_a2.setCheckable(True)
        self.btn_a2.setChecked(False)
        self.btn_a2.setObjectName("btn_a2")
        self.btn_a3 = QtWidgets.QPushButton(self.box_select)
        self.btn_a3.setGeometry(QtCore.QRect(220, 50, 62, 40))
        self.btn_a3.setText("")
        self.btn_a3.setCheckable(True)
        self.btn_a3.setChecked(False)
        self.btn_a3.setObjectName("btn_a3")
        self.btn_a4 = QtWidgets.QPushButton(self.box_select)
        self.btn_a4.setGeometry(QtCore.QRect(290, 50, 62, 40))
        self.btn_a4.setText("")
        self.btn_a4.setCheckable(True)
        self.btn_a4.setChecked(False)
        self.btn_a4.setObjectName("btn_a4")
        self.btn_a5 = QtWidgets.QPushButton(self.box_select)
        self.btn_a5.setGeometry(QtCore.QRect(360, 50, 62, 40))
        self.btn_a5.setText("")
        self.btn_a5.setCheckable(True)
        self.btn_a5.setChecked(False)
        self.btn_a5.setObjectName("btn_a5")
        self.btn_b1 = QtWidgets.QPushButton(self.box_select)
        self.btn_b1.setGeometry(QtCore.QRect(80, 100, 62, 40))
        self.btn_b1.setText("")
        self.btn_b1.setCheckable(True)
        self.btn_b1.setChecked(False)
        self.btn_b1.setObjectName("btn_b1")
        self.btn_b2 = QtWidgets.QPushButton(self.box_select)
        self.btn_b2.setGeometry(QtCore.QRect(150, 100, 62, 40))
        self.btn_b2.setText("")
        self.btn_b2.setCheckable(True)
        self.btn_b2.setChecked(False)
        self.btn_b2.setObjectName("btn_b2")
        self.btn_b3 = QtWidgets.QPushButton(self.box_select)
        self.btn_b3.setGeometry(QtCore.QRect(220, 100, 62, 40))
        self.btn_b3.setText("")
        self.btn_b3.setCheckable(True)
        self.btn_b3.setChecked(False)
        self.btn_b3.setObjectName("btn_b3")
        self.btn_b4 = QtWidgets.QPushButton(self.box_select)
        self.btn_b4.setGeometry(QtCore.QRect(290, 100, 62, 40))
        self.btn_b4.setText("")
        self.btn_b4.setCheckable(True)
        self.btn_b4.setChecked(False)
        self.btn_b4.setObjectName("btn_b4")
        self.btn_b5 = QtWidgets.QPushButton(self.box_select)
        self.btn_b5.setGeometry(QtCore.QRect(360, 100, 62, 40))
        self.btn_b5.setText("")
        self.btn_b5.setCheckable(True)
        self.btn_b5.setChecked(False)
        self.btn_b5.setObjectName("btn_b5")
        self.list_person = QtWidgets.QListWidget(self.box_edit)
        self.list_person.setGeometry(QtCore.QRect(10, 10, 121, 261))
        self.list_person.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.list_person.setObjectName("list_person")
        self.btn_add = QtWidgets.QPushButton(self.box_edit)
        self.btn_add.setGeometry(QtCore.QRect(250, 230, 81, 41))
        self.btn_add.setObjectName("btn_add")
        self.line_edit = QtWidgets.QLineEdit(self.box_edit)
        self.line_edit.setGeometry(QtCore.QRect(140, 230, 113, 41))
        self.line_edit.setObjectName("line_edit")
        self.btn_remove = QtWidgets.QPushButton(self.box_edit)
        self.btn_remove.setEnabled(False)
        self.btn_remove.setGeometry(QtCore.QRect(340, 230, 81, 41))
        self.btn_remove.setObjectName("btn_remove")
        self.btn_generate = QtWidgets.QPushButton(self.box_edit)
        self.btn_generate.setEnabled(False)
        self.btn_generate.setGeometry(QtCore.QRect(440, 230, 131, 41))
        self.btn_generate.setObjectName("btn_generate")
        self.label_13 = QtWidgets.QLabel(self.box_edit)
        self.label_13.setGeometry(QtCore.QRect(140, 180, 131, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.limit_times = QtWidgets.QSpinBox(self.box_edit)
        self.limit_times.setGeometry(QtCore.QRect(270, 180, 57, 30))
        self.limit_times.setMaximum(4)
        self.limit_times.setProperty("value", 3)
        self.limit_times.setObjectName("limit_times")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "网园无课表生成器"))
        self.label_6.setText(_translate("widget", "周三"))
        self.label_3.setText(_translate("widget", "56 节"))
        self.label_5.setText(_translate("widget", "周二"))
        self.label.setText(_translate("widget", "周一"))
        self.label_8.setText(_translate("widget", "周五"))
        self.label_4.setText(_translate("widget", "78 节"))
        self.label_7.setText(_translate("widget", "周四"))
        self.btn_add.setText(_translate("widget", "添加"))
        self.line_edit.setPlaceholderText(_translate("widget", "输入姓名"))
        self.btn_remove.setText(_translate("widget", "移除"))
        self.btn_generate.setText(_translate("widget", "生成值班表"))
        self.label_13.setText(_translate("widget", "每人最多值班次数："))

import res_rc
